config/routes.rb
Rails.application.routes.draw do
  get 'angular/show'

  get 'like/index'

  resources :entries, defaults: { format: 'json' }
  get 'raffle/index'

  get 'git_http/show'

  resources :widgets
  get 'hello_angular/show'
  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/models/hello_angular.rb
class HelloAngular < ActiveRecord::Base
var phonecatApp = angular.module('phonecatApp', []);
end

app/models/widget.rb
class Widget < ActiveRecord::Base

  validates :price, presence: true, numericality: { greater_than: 10 }
  validates :name, presence: true, length: { minimum: 7 }

end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
   respond_to :json
 
   def index
     respond_with Entry.all
   end

   def show
    respond_with Entry.find(params[:id])
   end
   
   def create
    respond_with Entry.create(params[:entry])
   end

   def update
    respond_with Entry.update(params[:id], params[:entry])
   end
   
   def destroy
   respond_with Entry.destroy(params[:id])
   end
end

app/controllers/git_http_controller.rb
class GitHttpController < ApplicationController
  def show
  end
end

app/controllers/hello_angular_controller.rb
class HelloAngularController < ApplicationController
  def show
  end
end

app/controllers/raffle_controller.rb
class RaffleController < ApplicationController
  def index
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/angular/show.html.erb
<p>Click the table headers to change the sorting order:</p>

<div ng-app="myApp" ng-controller="namesCtrl">
  <h1>{{myHeader}}</h1>
    <p>Search word with--><input type="text" ng-model="test"></p>

    <table border="1" width="100%">
      <tr>
        <th> # </th>
        <th ng-click="orderByMe('name')">Name</th>
        <th ng-click="orderByMe('country')">Country</th>
      </tr>
      <tr ng-repeat="x in names | orderBy:myOrderBy | filter:test">
        <td>{{ $index + 1 }}</td>
        <td>{{x.name}}</td>
        <td>{{x.country}}</td>
      </tr>
    </table>

  <h1 ng-click="changeName()">Click --> {{firstname}}</h1>

  <button ng-click="myFunc()">Click Me!</button>

  <div ng-show="showMe">
    <h1>Menu:</h1>
    <div>Pizza</div>
    <div>Pasta</div>
    <div>Pesce</div>
  </div>
  
  <div  class="card" >
  <header class="header">
    <h3>My Shopping List</h3>
  </header>
  <ul >
    <li ng-repeat="x in products">{{x}}<span ng-click="removeItem($index)" >  <button> <-- click me to delete</button> </span></li>
  </ul>
  <div >
    <div >
      <div>
        <input placeholder="Add shopping items here" ng-model="addMe" class="w3-input w3-border w3-padding">
      </div>
      <div >
        <button ng-click="addItem()" >Add</button>
      </div>
    </div>
    <p >{{errortext}}</p>
  </div>
</div>

</div>

app/views/git_http/show.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="GitHttpController">
   <div class="col-md-6">
    <h1>Git $http</h1>
 <form ng-submit="search()">
 <div class="input-group">
 <span class="input-group-addon">
 
 </span>
 <input type="text" class="form-control" placeholder="Git Username" ng-model="username">
 </div>
 </form>
   <hr />

  <div class="alert alert-danger" ng-show="errorMessage">
    <strong><i class="icon-warning-sign"></i> Error!</strong>
     {{ errorMessage }}
  </div>

<i class="icon-refresh icon-spin" ng-show="searching"></i>

 <ul class="list-group">
  <li class="list-group-item" ng-repeat="repo in repos">
    <h4 class="list-group-item-heading">{{ repo.full_name }}</h4>
     <p class="list-group-item-text text-muted">{{ repo.url }}</p>
     <p class="list-group-item-text text-muted">{{ repo.created_at }}</p>
 </li>
 </ul>
 </div>
 </div>

app/views/hello_angular/show.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="HelloWorldController">
    <div class="col-md-6">
        <h1>Hello AngularJS</h1>
     <p>Type in the input box and watch as AngularJS updates the property through \
                  the magic of binding.</p>
     
    <input type="text" class="form-control" ng-model="myText"  required>
                      {{ myText }}
    </div>

     <div class="col-md-6">
  <ul>
    <li ng-repeat="phone in phones">
      <span>{{phone.name}}</span>
      <p>{{phone.snippet}}</p>
    </li>
  </ul>
  <p>Total number of phones: {{phones.length}}</p>
  <p>Hello {{name}}!</p>

  <table>
      <tr><th>Row number</th></tr>
      <tr ng-repeat="i in [0, 1, 2, 3, 4, 5, 6, 7]"><td>{{i}}</td></tr>
  </table>

  <table >
     <tr><th>Row number</th></tr>
     <tr ng-repeat="i in [0, 1, 2, 3, 4, 5, 6, 7]"><td  ng-repeat="j in [0, 1, 2, 3, 4, 5, 6, 7]">demo</td></tr>            
  </table>

  <p>1 + 2 = {{1 + 2}}</p>

  </div>
 </div>
</div>

<style>
input.ng-invalid {
    background-color: lightblue;
}
</style>



  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
   
 <title><%= content_for?(:title) ? yield(:title) : "Angularails" %></title>
  <title>Angularails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse">
 <div class="container">
 <a class="navbar-brand" href="#">Angularails</a>
Hello AngularJS 8
 </div>
 </div>
 <div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/raffle/index.html.erb
    <h1>Raffle#index</h1>
<div class="row" ng-app="Raffler"  ng-controller="RaffleCtrl">

<form ng-submit="addEntry()">
  <input type="text" ng-model="newEntry.name">
  <input type="submit" value="Add">
</form>



 <ul>
  <li ng-repeat="entry in entries">
         {{entry.name}} {{entry.likes}}
     <p>
     <button ng-click="entry.likes=entry.likes+1"> PlusOne! </button>
     <span ng-show="entry.winner" ng-class= "{highlight: entry == lastWinner}"class="winner"> WINNER</span>
     <button ng-click="entry.likes=entry.likes-1"> MinusOne! </button>
  </li>
 </ul>
  <p>
  <button ng-click="drawWinner()"> Draw Winner! </button>
</div>

app/views/widgets/_form.html.erb
 <div ng-app="AngulaRails">
  <%= form_for @widget, id: "widgetForm", html: { name: "widgetForm", "novalidate" => true } do |f| %>
   <% if @widget.errors.any? %>
    <div class="alert alert-danger">>
      <h4><%= pluralize(@widget.errors.count, "error") %> </h4>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group" ng-class="{ 'has-error': widgetForm['widget[name]'].$invalid }">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", "ng-model" => "name", required: true, "ng-minlength" => "7" %>
   <span class="help-block" ng-show="widgetForm['widget[name]'].$error.required">Required</span>
   <span class="help-block" ng-show="widgetForm['widget[name]'].$error.minlength">Minimum length of 7</span>
  </div>
  <div class="form-group" ng-class="{ 'has-error': widgetForm['widget[price]'].$invalid }">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control", "ng-model" => "price", required: true, "min" => "10"  %>
 <span class="help-block" ng-show="widgetForm['widget[price]'].$error.required">Required</span>
<span class="help-block" ng-show="widgetForm['widget[price]'].$error.min">Most be greater than 10</span>
  </div>
    <%= f.submit  "Save", class: "btn btn-primary", "ng-disabled" => "widgetForm.$invalid"  %>
<% end %>
</div>

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.price %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @widget.price %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>